### ISSUE TITLE
addSubscribersToList not working

### ISSUE THREAD

**Issue by JordashTalon** [klaviyo/node-klaviyo#11]
I can't seem to get this to work, here is the code:

```
let response = await KlaviyoClient.lists.addSubscribersToList({
        listId: 'hidden',
        profiles: [
            {
                email: 'testeremail523@mailinator.com',
            }
        ]
})
    
console.log(response, 'response data');
```

The response data comes back as [] and no user is added to the list, I tried non mailinator emails as well, any Idea what I'm doing wrong?

**Comment by smoucka** [comment]
Hi @JordashTalon 

The addSubscribersToList method uses Klaviyo's v2 Subscribe endpoint which adheres to the double opt-in settings on the list. In order to add someone to a list with double opt-in enabled they will need to confirm their subscription, more information here: https://help.klaviyo.com/hc/en-us/articles/115005251108-Guide-to-The-Double-Opt-In-Process

Let us know if that doesn't solve the issue for you.

**Comment by aoppenh** [comment]
I am having this same problem, with both addSubscribersToList and sending a POST request manually.  Has there been any update on this?

**Comment by JordashTalon** [comment]
@aoppenh What @smoucka helped, if you have double opt-in enabled by default, it won't add the user to the email list until they get the opt-in email and click verify.

There's another method:
KlaviyoClient.lists.addMembersToList

That adds the user regardless of the opt-in settings, to that one is a bit easier to test with.

**Comment by aoppenh** [comment]
@JordashTalon I actually found out what the problem is, and it's just one of those moments.  I had the listId slightly wrong in my test site with a "g" in it, while in the aws test I was running it was correct and that character was a "q", I must have stared at aws logs for hours before I noticed it.  Just one of those days...
