### ISSUE TITLE
Klaviyo data not appearing using track api

### ISSUE THREAD

**Issue by jontremelling** [klaviyo/node-klaviyo#14]
When sending multiple requests within a short space of time (about 5 in under a second), the api only seems to send data for some of them. Despite getting five success responses, data on the Klaviyo website never appears for some calls.

If I add a wait between calls of about 1 second, all data gets sent successfully, but according to the Klaviyo documentation, if we receive a 1, the call has been successful and any data will appear in Klaviyo shortly.

**Comment by remstone7** [comment]
Hey @jontremelling what calls are you making?  We have a very basic validation check esssentially making sure the data and required properties are set but down stream there is additional validation that would check to see if a duplicate event is found.  Ex. if you're sending multiple ordered product events to the same user and they have the same timestamp, only 1 would be recorded.  You would want to include a unique $event_id to ensure they're all captured, otherwise we utilize the timestamp as the unique $event_id and would de dupe from there. 
https://help.klaviyo.com/hc/en-us/articles/115000751052-Track-and-Identify-API-Reference#reserved-event-properties11

**Comment by jontremelling** [comment]
Thanks @remstone7, that looks to be the issue! I have included $event_id and all is working now.
Interestingly, all I had to do is assign a new timestamp to $event_id, which should be what happens if I don't supply it at all.

Maybe the default doesn't include ms so would appear to be a duplicate.
