### ISSUE TITLE
CORS Allow Origin not working for "public" APIs

### ISSUE THREAD

**Issue by JeffJassky** [klaviyo/node-klaviyo#33]
When using in a browser-based client (Chrome, Firefox, etc), the public APIs (identify & track) do not work as expected.

The requests fail due to "Allow Origin" headers not being present. Both GET and POST requests are subject to this issue.

Solution: Add support for Allow Origin headers.

**Comment by njparadis** [comment]
Hey @JeffJassky! Are you seeing this issue when using node-klaviyo specifically? These two endpoints are used by the Klaviyo [client-side Javascript library](https://apidocs.klaviyo.com/reference/javascript-client-library) and should be served with the appropriate CORS headers.

**Comment by JeffJassky** [comment]
@njparadis I worked around the issue by taking `node-klaviyo` off of the client and instead using it from my server. That is sufficient for my needs.

However, for anyone interested, here are more details:

I was seeing this issue using `node-klaviyo` specifically. I have not yet tried directly using the client-side javascript library that you linked to. 

Can you clarify what you meant by `These two endpoints are used by the Klaviyo client-side Javascript library and should be served with the appropriate CORS headers.`? Are you suggesting that the other javascript library should be used for client side instead because `node-klaviyo` doesn't use the aooropriate CORS headers? Or are you suggesting that `node-klaviyo` is configured with the appropriate CORS headers and should work on a client as-is?

Thank you!

**Comment by njparadis** [comment]
Thanks for the additional context @JeffJassky - perhaps I've misunderstood which CORS headers are missing.

From your initial description of the issue, it sounds like you ran into the error due to a missing `access-control-allow-origin` header. From my understanding of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests) this header is returned on the response from the server (a.klaviyo.com) versus something we would set in the SDK.

That being said, I recommend using the APIs available from klaviyo.js (_learnq) if you need to track/identify users in a client-side environment.
